apiVersion: v1
kind: Service
metadata:
  name: event-handler-svc
  namespace: vnext-apps
  annotations:
    prometheus/scrape: "true"
    prometheus/scheme: "http"
    prometheus/path: "/metrics"
    prometheus/port: "3502"
spec:
  selector:
    app: event-handler-svc
  ports:
    - port: 3502 #this must match SVC_DEFAULT_HTTP_PORT or metrics port
  type: LoadBalancer
