apiVersion: v1
kind: Service
metadata:
  name: transfers-api-svc
  namespace: vnext-apps
spec:
  selector:
    app: transfers-api-svc
  ports:
    - port: 80
      targetPort: 3500
  type: LoadBalancer
